version: 0.2

phases:
  install:
    commands:
      - echo "Updating OS packages and installing necessary tools..."
      - apt-get install -y unzip jq curl make bash
      - echo "Fetching the latest Terraform version..."
      - echo "Fetching the latest Terraform version..."
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - "mv terraform /bin"
      - "rm terraform.zip"
      - terraform version
      - echo "Verifying installations..."
      - bash --version
      - make --version
      - echo "AWS CLI Version:"
      - aws --version
      - aws configure set output json --profile default

  pre_build:
    commands:
      - echo "Navigating to project directory..."
      - cd single-account-single-cluster-multi-env
      - echo "Deploying Terraform resources for state management..."
      - set -ex
      - codebuild-breakpoint
      - make bootstrap"

  build:
    commands:
      - echo "Navigating to Terraform vars directory..."
      - cd 00.global/vars
      - echo "Environment files found:"
      - ls -al  # List the environment configuration files
      - cd ../../  # Navigate back to the root of the Terraform directory
      - set -ex
      - codebuild-breakpoint
      - make apply-all

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  discard-paths: yes

env:
  variables:
    AWS_REGION: "eu-central-1"
    AWS_PROFILE: "default"
    ENVIRONMENT: "dev"  # You can adjust this as needed
    TF_VERSION: "1.8.0"