version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Updating OS packages and installing necessary tools..."
      - apt-get install -y unzip jq curl make bash
      - echo "Verifying installations..."
      - bash --version
      - make --version
      - echo "AWS CLI Version:"
      - aws --version

  pre_build:
    commands:
      - echo "Navigating to project directory..."
      - cd single-account-single-cluster-multi-env
      - echo "Deploying Terraform resources for state management..."
      - set -ex
      - codebuild-breakpoint
      - /bin/bash -c "set -o pipefail && make bootstrap"

  build:
    commands:
      - echo "Navigating to Terraform vars directory..."
      - cd 00.global/vars
      - echo "Environment files found:"
      - ls -al  # List the environment configuration files
      - cd ../../  # Navigate back to the root of the Terraform directory
      - set -ex
      - codebuild-breakpoint
      - /bin/bash -c "set -o pipefail && make bootstrap"

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  discard-paths: yes

env:
  variables:
    AWS_REGION: "eu-central-1"
    ENVIRONMENT: "dev"  # You can adjust this as needed